'use client';
import Link from 'next/link';
import { UsersRound, CalendarCheck2, Wallet, Clock3, Plus, ArrowLeft, CalendarPlus, Receipt, Gift, FileChartColumnIncreasing, UserRoundPlus, ClipboardCheck, CircleHelp, ShieldCheck, ChevronLeft } from 'lucide-react';
import { useDemo } from '@/components/demo-provider';
import { Badge, Card, StatCard, Avatar, EmptyState } from '@/components/ui';
import { DEMO_MONTH, DEMO_TODAY } from '@/lib/mock-data';
import { getMonthPayroll } from '@/lib/payroll';
import { money, number, monthLabel, time, duration } from '@/lib/format';
import { statusLabel } from '@/lib/attendance';

export default function DashboardPage() {
  const { data, session } = useDemo();
  const day = data.workdays.find(item => item.date === DEMO_TODAY);
  const records = data.attendance.filter(item => item.workdayId === day?.id);
  const present = records.filter(item => item.status === 'PRESENT');
  const unresolved = records.filter(item => item.status === 'UNRESOLVED');
  const absent = records.filter(item => item.status === 'EXCUSED' || item.status === 'UNEXCUSED');
  const late = present.filter(item => item.latenessSeconds > 0);
  const expected = records.filter(item => item.status !== 'EXEMPT').length;
  const payroll = getMonthPayroll(data, DEMO_MONTH);
  const total = payroll.reduce((sum,item) => sum + item.finalSalary,0);
  const unpaid = payroll.filter(item => item.paymentStatus !== 'PAID');
  const adjustments = payroll.reduce((sum,item) => sum + item.otherDeductions,0);
  const bonuses = payroll.reduce((sum,item) => sum + item.bonuses,0);
  const actions = [{label:'فتح يوم حضور',href:'/workdays?open=new',icon:CalendarPlus},{label:'إضافة موظف',href:'/employees?add=1',icon:UserRoundPlus},{label:'إضافة خصم',href:'/deductions?add=1',icon:Receipt},{label:'إضافة مكافأة',href:'/bonuses?add=1',icon:Gift}];
  return <div className="page-stack"><header className="page-header"><div><div className="welcome-line"><span className="line"/>الاثنين، 28 أيلول 2026</div><h1>صباح الخير، {session?.name.split(' ')[0]}.</h1><p>صورة واضحة لمركزك. كل ما تحتاجه لمتابعة يوم العمل.</p></div><div className="page-actions"><Link className="btn btn-secondary" href="/reports"><FileChartColumnIncreasing size={17}/>عرض التقارير</Link><Link className="btn btn-primary" href="/workdays?open=new"><Plus size={17}/>فتح يوم حضور</Link></div></header>
    <div className="stats-grid"><StatCard label="الموظفون الفعّالون" value={number(data.employees.filter(e=>e.active).length)} hint={`${data.departments.filter(d=>d.active).length} أقسام تعمل كفريق واحد`} icon={<UsersRound/>}/><StatCard label="الحاضرون اليوم" value={present.length} hint={`من أصل ${expected} موظفاً مطلوباً`} icon={<CalendarCheck2/>}/><StatCard label="بانتظار مراجعتك" value={unresolved.length} hint="موظفون لم تُحسم حالة حضورهم" icon={<Clock3/>}/><StatCard label="صافي رواتب الشهر" value={<>{number(total)} <small style={{fontSize:11,letterSpacing:0}}>د.ع</small></>} hint={monthLabel(DEMO_MONTH)} icon={<Wallet/>} accent/></div>
    <div className="dashboard-split"><Card title="متابعة حضور اليوم" description="الحضور والانضباط، بنظرة واحدة" action={<Badge tone={day?.state === 'OPEN' ? 'success':'neutral'}>{day?.state === 'OPEN' ? 'اليوم مفتوح' : day ? 'اليوم مغلق':'لم يُفتح اليوم'}</Badge>}>{day ? <><div className="today-summary"><div><div className="big-metric">{expected ? Math.round(present.length / expected * 100) : 0}<small> %</small></div><span className="muted" style={{fontSize:10}}>نسبة الحضور حتى الآن</span></div><div style={{textAlign:'left'}}><div className="muted" style={{fontSize:10}}>بداية الدوام</div><strong dir="ltr" style={{fontSize:13}}>{time(day.startTime)}</strong></div></div><div className="progress-track" role="img" aria-label={`حاضر ${present.length}، غير محسوم ${unresolved.length}، غائب ${absent.length}`}><span style={{width:`${present.length / (expected || 1) * 100}%`}}/><span className="pending" style={{width:`${unresolved.length / (expected || 1) * 100}%`}}/><span className="absent" style={{width:`${absent.length / (expected || 1) * 100}%`}}/></div><div className="attendance-legend"><div className="legend-item"><span><i/>حاضر</span><strong>{present.length}</strong></div><div className="legend-item"><span><i/>غير محسوم</span><strong>{unresolved.length}</strong></div><div className="legend-item"><span><i/>غائب</span><strong>{absent.length}</strong></div></div><div className="card-bottom"><span>{late.length} موظفين سجّلوا حضوراً متأخراً</span><Link className="button-link" href="/attendance">مراجعة حضور اليوم<ArrowLeft size={14}/></Link></div></> : <EmptyState title="لم يتم فتح يوم حضور اليوم" action={<Link className="btn btn-primary" href="/workdays">فتح يوم حضور</Link>}/>}</Card><Card title="اختصارات يومك" description="أهم الإجراءات، بخطوة واحدة"><div className="quick-actions">{actions.map(action=><Link key={action.href} className="quick-action" href={action.href}><action.icon/><span>{action.label}</span></Link>)}</div><div className="quick-note"><CircleHelp size={17}/><span>ابدأ بمراجعة الموظفين غير المحسومين قبل إغلاق يوم الحضور.</span></div><div className="card-bottom"><span>الرواتب غير المصروفة أو قيد المراجعة</span><Link className="button-link" href="/payroll">{unpaid.length} موظفين<ChevronLeft size={14}/></Link></div></Card></div>
    <Card title="آخر تسجيلات الحضور" description="آخر حركة حضور مسجلة في يوم العمل" action={<Link className="button-link" href="/attendance">كل السجل<ArrowLeft size={14}/></Link>}><div className="table-wrap desktop-table"><table className="data-table"><thead><tr><th>الموظف</th><th>القسم</th><th>وقت الحضور</th><th>التأخير</th><th>الحالة</th></tr></thead><tbody>{[...present].sort((a,b)=>(b.checkIn||'').localeCompare(a.checkIn||'')).slice(0,4).map(record=>{const employee=data.employees.find(e=>e.id===record.employeeId)!;return <tr key={record.id}><td><Link href={`/employees/${employee.id}`} className="employee-cell"><Avatar name={employee.name}/><div><strong>{employee.name}</strong><span className="subtext" dir="ltr">{employee.code}</span></div></Link></td><td>{data.departments.find(d=>d.id===employee.departmentId)?.name}</td><td dir="ltr" style={{textAlign:'right'}}>{time(record.checkIn||'')}</td><td className={record.latenessSeconds ? 'text-brand':'muted'}>{duration(record.latenessSeconds)}</td><td><Badge tone="success">{statusLabel(record.status)}</Badge></td></tr>})}</tbody></table></div><div className="mobile-cards">{present.slice(0,4).map(record=>{const employee=data.employees.find(e=>e.id===record.employeeId)!;return <Link className="list-row" key={record.id} href={`/employees/${employee.id}`}><div className="inline"><Avatar name={employee.name}/><div><strong>{employee.name}</strong><p>{duration(record.latenessSeconds)}</p></div></div><span dir="ltr" style={{fontSize:10}}>{time(record.checkIn||'')}</span></Link>})}</div>{!present.length && <EmptyState title="لا توجد تسجيلات حضور بعد"/>}</Card>
    <div className="dashboard-lower"><Card title="الفريق حسب الأقسام" description="توزيع الموظفين الفعّالين" action={session?.role==='SUPER_ADMIN' ? <Link className="button-link" href="/departments">إدارة الأقسام<ChevronLeft size={14}/></Link>:undefined}><div className="department-bars">{data.departments.filter(d=>d.active).map(department=>{const count=data.employees.filter(e=>e.departmentId===department.id&&e.active).length;return <div key={department.id}><div className="department-bar-top"><span>{department.name}</span><span>{count} موظفين</span></div><div className="department-bar-track"><span style={{width:`${count / Math.max(...data.departments.map(d=>data.employees.filter(e=>e.departmentId===d.id&&e.active).length),1) * 100}%`}}/></div></div>})}</div></Card><Card title="آخر العمليات" description="متابعة ما تغيّر في مركزك" action={session?.role==='SUPER_ADMIN' ? <Link className="button-link" href="/audit">سجل العمليات<ChevronLeft size={14}/></Link>:undefined}>{data.audit.slice(0,4).map(item=><div className="activity-row" key={item.id}><span className="activity-dot"><ClipboardCheck size={15}/></span><div><p>{item.action}</p><small>{item.actor}</small></div><time dir="ltr">{time(item.timestamp)}</time></div>)}<div className="card-bottom"><span className="inline"><ShieldCheck size={14}/>الخصومات: {money(adjustments)}</span><span>المكافآت: {money(bonuses)}</span></div></Card></div>
  </div>;
}
